# Base URL
baseurl:

# Site live URL
url: http://brilhana.github.io

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Alexandre Brilhante
  # Little description about your site
  description:
  date_format: "%D"
  meta_description: > #
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Alexandre Brilhante
    email: alexandre.brilhante@umontreal.ca
    url: http://brilhana.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social:
    github: brilhana
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed